add firstGetApi testScenario
ladap1999/Qase_TAF pull request #2
Opened 2023-02-26 02:43 UTC by ladap1999

2023-02-26 11:53 UTC, SMeleshk requested changes

2023-02-26 11:53 UTC, SMeleshk commented on src/test/java/models/ProjectResponseModel.java
> +    private String code;
А зачем отдельно Project и ProjectResponse модели?
В ProjectResponse нужны title и code поля, которые уже есть в Project, их ведь можно использовать?

2023-02-26 11:53 UTC, SMeleshk commented on src/test/resources/config.properties
> +url=https://api.qase.io/v1
С url есть проблема: мы не сможем в iu и api тестах использовать один и тот же, тк базовый url для ui - это https://app.qase.io.
Предлагаю переименовать оба:
apiUrl = https://api.qase.io/v1
uiUrl = https://app.qase.io

И, соответственно, методы в ReadProperties переименовать на 
getApiUrl и getUiUrl

2023-02-26 18:10 UTC, ladap1999 commented on src/test/java/models/ProjectResponseModel.java
> +    private String code;
![image](https://user-images.githubusercontent.com/48569567/221428286-ba9f8682-fa5a-48a7-bfbd-b0a297822621.png)
![image](https://user-images.githubusercontent.com/48569567/221428348-df7bb9d4-5d31-43e2-98cb-941d99abe427.png)
Я думаю, что на response и на post body используются разные объекты, т.к поля для заполнения разные по документации

2023-02-26 18:13 UTC, ladap1999 commented on src/test/resources/config.properties
> +url=https://api.qase.io/v1
исправила

2023-02-28 18:26 UTC, SMeleshk approved these changes

2023-02-28 18:27 UTC, merged