develop -> master
ladap1999/Qase_TAF pull request #5
Opened 2023-03-01 22:28 UTC by ladap1999

2023-03-05 06:14 UTC, wildpioneer requested changes

2023-03-05 06:14 UTC, wildpioneer commented on src/main/java/factory/BrowserFactory.java
> +                System.out.println("Browser " + ReadProperties.browserName() + " is not supported.");
Все выводы на консоль должны быть через Logger

2023-03-05 06:14 UTC, wildpioneer commented on src/main/java/services/WaitsService.java
> +    public WebElement fluentWaitForElement(By by) {
Все неиспользуемые методы должны быть убраны из финальной работы

2023-03-05 21:27 UTC, SMeleshk commented on src/main/java/services/WaitsService.java
> +    public WebElement fluentWaitForElement(By by) {
Убрали и будем иметь в виду в будущем.

2023-03-05 21:27 UTC, SMeleshk commented on src/main/java/factory/BrowserFactory.java
> +                System.out.println("Browser " + ReadProperties.browserName() + " is not supported.");
Исправлено

2023-03-13 16:32 UTC, SMeleshk approved these changes

2023-03-13 18:45 UTC, wildpioneer approved these changes

2023-03-13 18:45 UTC, wildpioneer commented on src/test/java/pages/CreateCasePage.java
> +    private final By validationMessageLocator = By.xpath("//*[@id = 'titleGroup']/*[@class = 'form-control-feedback']");
Тут можно было проще с использованием CSS #titleGroup .form-control-feedback

2023-03-13 18:45 UTC, merged

2023-03-13 18:46 UTC, wildpioneer commented
Прекрасно - только с двойным лавированием у меня сомнения